sudo: required
services:
  - docker

before_install:
  - docker build -t zhmakas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true zhmakas/react-test npm test

after_success:
  - docker build -t zhmakas/multi-client ./client
  - docker build -t zhmakas/multi-nginx ./nginx
  - docker build -t zhmakas/multi-server ./server
  - docker build -t zhmakas/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push zhmakas/multi-client
  - docker push zhmakas/multi-nginx
  - docker push zhmakas/multi-server 
  - docker push zhmakas/multi-worker